import { isRealIsoDate } from "./dateValidation";

export const OPERATOR_IMPORT_SCHEMA = "vogel-vault.ledger-batch/v1" as const;
export const OPERATOR_IMPORT_MAX_OPS = 100;

const I64_MIN = -(1n << 63n);
const I64_MAX = (1n << 63n) - 1n;
const CONTROL = /[\u0000-\u001f\u007f]/u;
const IDENTIFIER = /^[A-Za-z0-9][A-Za-z0-9._:@/-]*$/u;
const SHA256 = /^[0-9a-f]{64}$/u;

export type ImportOwner = "victor" | "rachel" | "mason" | "maddox";
export type ImportKind = "transaction" | "income" | "btc_buy" | "btc_bill_pay";
type Common = { op_id: string; record_id: string; source_locator: string; owner: ImportOwner; date: string };
export type ImportTransaction = Common & { kind: "transaction"; source_file: "transactions" | "mason-transactions" | "maddox-transactions"; merchant: string; amount_cents: bigint; transaction_kind: "spend" | "credit"; category: string; card?: string; note?: string; supersedes_record_id?: string };
export type ImportIncome = Common & { kind: "income"; source_file: "income"; amount_cents: bigint; source: string; logged_by?: string; note?: string; archimedes_request_id?: string };
export type ImportBtcBuy = Common & { kind: "btc_buy"; source_file: "bitcoin-buys" | "mason-bitcoin-buys"; source: string; sats: bigint; price_usd_cents: bigint; usd_cents: bigint; note?: string; status?: string; cost_basis_status?: string; logged_by?: string; archimedes_request_id?: string };
export type ImportBtcBillPay = Common & { kind: "btc_bill_pay"; source_file: "bitcoin-bill-pays"; merchant: string; category: string; amount_usd_cents: bigint; btc_spent_sats: bigint; btc_price_cents: bigint; fee_usd_cents: bigint; platform?: string; note?: string; reference?: string; budget_effect: "excluded_from_transactions" };
export type OperatorImportOp = ImportTransaction | ImportIncome | ImportBtcBuy | ImportBtcBillPay;
export type SemanticDuplicateAttestation = { type: "semantic_duplicate"; op_ids: readonly [string, string]; semantic_fingerprint: string; assertion: "distinct_real_world_records" };
export type BudgetAdvance = { source_file: "budget"; expected_month: string; target_month: string; expected_updated_at_ms: number; history_mode: "preserve_existing" };
export type OperatorImportEnvelope = { schema: typeof OPERATOR_IMPORT_SCHEMA; batch_id: string; ops: OperatorImportOp[]; duplicate_attestations: SemanticDuplicateAttestation[]; budget_advance?: BudgetAdvance };
export type CanonicalOperatorImportOp = OperatorImportOp & { natural_key: string; semantic_fingerprint: string };
export type CanonicalOperatorImport = { envelope: OperatorImportEnvelope; ops: CanonicalOperatorImportOp[]; counts: Record<ImportKind, number>; canonical_json: string; manifest_digest: string };

export class OperatorImportValidationError extends Error {
  constructor(readonly code: string, readonly path: string, message: string, readonly metadata?: Readonly<Record<string, string | readonly string[]>>) { super(message); this.name = "OperatorImportValidationError"; }
}
function fail(code: string, path: string, message: string): never { throw new OperatorImportValidationError(code, path, message); }
function objectAt(value: unknown, path: string): Record<string, unknown> { if (value === null || typeof value !== "object" || Array.isArray(value)) fail("INVALID_TYPE", path, `${path} must be an object`); return value as Record<string, unknown>; }
function exactKeys(row: Record<string, unknown>, required: readonly string[], optional: readonly string[], path: string) { const allowed = new Set([...required, ...optional]); for (const key of Object.keys(row)) if (!allowed.has(key)) fail("UNKNOWN_FIELD", `${path}.${key}`, `${path} contains an unknown field`); for (const key of required) if (!Object.prototype.hasOwnProperty.call(row, key)) fail("MISSING_FIELD", `${path}.${key}`, `${path}.${key} is required`); }
function literalAt<T extends string>(value: unknown, allowed: readonly T[], path: string): T { if (typeof value !== "string" || !allowed.includes(value as T)) fail("INVALID_LITERAL", path, `${path} is not allowed`); return value as T; }
function textAt(value: unknown, path: string, max: number, identifier = false, allowEmpty = false): string { if (typeof value !== "string") fail("INVALID_TYPE", path, `${path} must be a string`); const valueNfc = value.normalize("NFC"); if ((!allowEmpty && valueNfc.length === 0) || valueNfc.length > max || CONTROL.test(valueNfc) || valueNfc !== valueNfc.trim()) fail("INVALID_TEXT", path, `${path} must be bounded canonical NFC text`); if (identifier && !IDENTIFIER.test(valueNfc)) fail("INVALID_IDENTIFIER", path, `${path} is not a canonical identifier`); return valueNfc; }
function optionalText(row: Record<string, unknown>, key: string, path: string, max = 16_384): string | undefined { return row[key] === undefined ? undefined : textAt(row[key], `${path}.${key}`, max, false, true); }
function int64At(value: unknown, path: string): bigint { if (typeof value !== "string" || !/^-?(?:0|[1-9][0-9]*)$/u.test(value) || value === "-0") fail("INVALID_INTEGER", path, `${path} must be a canonical decimal integer string`); const parsed = BigInt(value); if (parsed < I64_MIN || parsed > I64_MAX) fail("INTEGER_OUT_OF_RANGE", path, `${path} exceeds int64`); return parsed; }
function requireBtcTuple(sats: bigint, priceCents: bigint, usdCents: bigint, toleranceBps: bigint, path: string) { const scale = 100_000_000n; const implied = sats * priceCents; const target = usdCents * scale; const difference = implied >= target ? implied - target : target - implied; const allowed = (target * toleranceBps) / 10_000n + scale; if (difference > allowed) fail("INCONSISTENT_BTC_TUPLE", path, `${path} BTC and USD units are inconsistent`); }
// Real-date detection is dateValidation.isRealIsoDate — the same calendar rule
// the writeback and row paths enforce — instead of a third private copy of the
// leap-year and days-in-month tables. The leading shape check keeps this
// envelope's own INVALID_DATE message for malformed text.
function dateAt(value: unknown, path: string): string { if (typeof value !== "string" || !/^\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\d|3[01])$/u.test(value)) fail("INVALID_DATE", path, `${path} must be yyyy-MM-dd`); if (!isRealIsoDate(value)) fail("INVALID_DATE", path, `${path} is not a real date`); return value; }
function common(row: Record<string, unknown>, path: string): Common { return { op_id: textAt(row.op_id, `${path}.op_id`, 128, true), record_id: textAt(row.record_id, `${path}.record_id`, 256, true), source_locator: textAt(row.source_locator, `${path}.source_locator`, 512, true), owner: literalAt(row.owner, ["victor", "rachel", "mason", "maddox"], `${path}.owner`), date: dateAt(row.date, `${path}.date`) }; }
function ownerSource(op: OperatorImportOp, path: string) { const mapping: Record<string, readonly ImportOwner[]> = { transactions: ["victor"], "mason-transactions": ["mason"], "maddox-transactions": ["maddox"], income: ["victor"], "bitcoin-buys": ["victor"], "mason-bitcoin-buys": ["mason"], "bitcoin-bill-pays": ["victor", "rachel", "mason", "maddox"] }; if (!mapping[op.source_file]?.includes(op.owner)) fail("OWNER_SOURCE_MISMATCH", `${path}.owner`, "owner does not match source_file"); }

function parseOp(value: unknown, index: number): OperatorImportOp {
  const path = `ops[${index}]`; const row = objectAt(value, path); const kind = literalAt(row.kind, ["transaction", "income", "btc_buy", "btc_bill_pay"], `${path}.kind`); const base = ["kind", "op_id", "record_id", "source_locator", "owner", "source_file", "date"]; let op: OperatorImportOp;
  if (kind === "transaction") {
    exactKeys(row, [...base, "merchant", "amount_cents", "transaction_kind", "category"], ["card", "note", "supersedes_record_id"], path); const txKind = literalAt(row.transaction_kind, ["spend", "credit"], `${path}.transaction_kind`); const amount = int64At(row.amount_cents, `${path}.amount_cents`); const category = textAt(row.category, `${path}.category`, 128); if (amount === 0n || (txKind === "spend" ? amount < 0n : amount > 0n)) fail("INVALID_SIGN", `${path}.amount_cents`, "spend must be positive, credit negative, and zero is forbidden"); if (category === "Income") fail("INVALID_CATEGORY", `${path}.category`, "income transaction mirrors are forbidden"); const commonFields = common(row, path); const supersedes = row.supersedes_record_id === undefined ? undefined : textAt(row.supersedes_record_id, `${path}.supersedes_record_id`, 256, true); if (supersedes !== undefined && supersedes === commonFields.record_id) fail("CORRECTION_SELF_REFERENCE", `${path}.supersedes_record_id`, "a correction cannot supersede its own record id"); op = { ...commonFields, kind, source_file: literalAt(row.source_file, ["transactions", "mason-transactions", "maddox-transactions"], `${path}.source_file`), merchant: textAt(row.merchant, `${path}.merchant`, 256), amount_cents: amount, transaction_kind: txKind, category, card: optionalText(row, "card", path, 128), note: optionalText(row, "note", path), supersedes_record_id: supersedes };
  } else if (kind === "income") {
    exactKeys(row, [...base, "amount_cents", "source"], ["logged_by", "note", "archimedes_request_id"], path); const amount = int64At(row.amount_cents, `${path}.amount_cents`); if (amount <= 0n) fail("INVALID_SIGN", `${path}.amount_cents`, "income must be positive"); op = { ...common(row, path), kind, source_file: literalAt(row.source_file, ["income"], `${path}.source_file`), amount_cents: amount, source: textAt(row.source, `${path}.source`, 256), logged_by: optionalText(row, "logged_by", path, 128), note: optionalText(row, "note", path), archimedes_request_id: optionalText(row, "archimedes_request_id", path, 256) };
  } else if (kind === "btc_buy") {
    exactKeys(row, [...base, "source", "sats", "price_usd_cents", "usd_cents"], ["note", "status", "cost_basis_status", "logged_by", "archimedes_request_id"], path); const sats = int64At(row.sats, `${path}.sats`), price = int64At(row.price_usd_cents, `${path}.price_usd_cents`), usd = int64At(row.usd_cents, `${path}.usd_cents`); if (sats <= 0n || price <= 0n || usd <= 0n) fail("INVALID_SIGN", path, "BTC buy units must be positive"); requireBtcTuple(sats, price, usd, 200n, path); op = { ...common(row, path), kind, source_file: literalAt(row.source_file, ["bitcoin-buys", "mason-bitcoin-buys"], `${path}.source_file`), source: textAt(row.source, `${path}.source`, 256), sats, price_usd_cents: price, usd_cents: usd, note: optionalText(row, "note", path), status: optionalText(row, "status", path, 128), cost_basis_status: optionalText(row, "cost_basis_status", path, 128), logged_by: optionalText(row, "logged_by", path, 128), archimedes_request_id: optionalText(row, "archimedes_request_id", path, 256) };
  } else {
    exactKeys(row, [...base, "merchant", "category", "amount_usd_cents", "btc_spent_sats", "btc_price_cents", "fee_usd_cents"], ["platform", "note", "reference", "budget_effect"], path); const amount = int64At(row.amount_usd_cents, `${path}.amount_usd_cents`), sats = int64At(row.btc_spent_sats, `${path}.btc_spent_sats`), price = int64At(row.btc_price_cents, `${path}.btc_price_cents`), fee = int64At(row.fee_usd_cents, `${path}.fee_usd_cents`); if (amount <= 0n || sats <= 0n || price <= 0n || fee < 0n) fail("INVALID_SIGN", path, "bill-pay units must be positive and fee nonnegative"); requireBtcTuple(sats, price, amount + fee, 25n, path); op = { ...common(row, path), kind, source_file: literalAt(row.source_file, ["bitcoin-bill-pays"], `${path}.source_file`), merchant: textAt(row.merchant, `${path}.merchant`, 256), category: textAt(row.category, `${path}.category`, 128), amount_usd_cents: amount, btc_spent_sats: sats, btc_price_cents: price, fee_usd_cents: fee, platform: optionalText(row, "platform", path, 128), note: optionalText(row, "note", path), reference: optionalText(row, "reference", path, 256), budget_effect: row.budget_effect === undefined ? "excluded_from_transactions" : literalAt(row.budget_effect, ["excluded_from_transactions"], `${path}.budget_effect`) };
  }
  ownerSource(op, path); return op;
}

function parseAttestation(value: unknown, index: number): SemanticDuplicateAttestation { const path = `duplicate_attestations[${index}]`, row = objectAt(value, path); exactKeys(row, ["type", "op_ids", "semantic_fingerprint", "assertion"], [], path); if (!Array.isArray(row.op_ids) || row.op_ids.length !== 2) fail("INVALID_ATTESTATION", `${path}.op_ids`, "exactly two op ids required"); const first = textAt(row.op_ids[0], `${path}.op_ids[0]`, 128, true), second = textAt(row.op_ids[1], `${path}.op_ids[1]`, 128, true); if (first >= second) fail("INVALID_ATTESTATION", `${path}.op_ids`, "op ids must be distinct and sorted"); const fingerprint = textAt(row.semantic_fingerprint, `${path}.semantic_fingerprint`, 64); if (!SHA256.test(fingerprint)) fail("INVALID_ATTESTATION", `${path}.semantic_fingerprint`, "lowercase SHA-256 required"); return { type: literalAt(row.type, ["semantic_duplicate"], `${path}.type`), op_ids: [first, second], semantic_fingerprint: fingerprint, assertion: literalAt(row.assertion, ["distinct_real_world_records"], `${path}.assertion`) }; }

function parseBudgetAdvance(value: unknown): BudgetAdvance {
  const path = "batch.budget_advance";
  const row = objectAt(value, path);
  exactKeys(row, ["source_file", "expected_month", "target_month", "expected_updated_at_ms", "history_mode"], [], path);
  const expectedUpdatedAt = int64At(row.expected_updated_at_ms, `${path}.expected_updated_at_ms`);
  if (expectedUpdatedAt < 0n || expectedUpdatedAt > BigInt(Number.MAX_SAFE_INTEGER)) {
    fail("INVALID_REVISION", `${path}.expected_updated_at_ms`, "budget revision must be a nonnegative safe integer");
  }
  return {
    source_file: literalAt(row.source_file, ["budget"], `${path}.source_file`),
    expected_month: textAt(row.expected_month, `${path}.expected_month`, 64),
    target_month: textAt(row.target_month, `${path}.target_month`, 64),
    expected_updated_at_ms: Number(expectedUpdatedAt),
    history_mode: literalAt(row.history_mode, ["preserve_existing"], `${path}.history_mode`),
  };
}

export function parseOperatorImportEnvelope(input: unknown): OperatorImportEnvelope { const root = objectAt(input, "batch"); exactKeys(root, ["schema", "batch_id", "ops"], ["duplicate_attestations", "budget_advance"], "batch"); if (!Array.isArray(root.ops) || root.ops.length < 1 || root.ops.length > OPERATOR_IMPORT_MAX_OPS) fail("INVALID_OPERATION_COUNT", "batch.ops", "batch must contain 1-100 operations"); const rawAttestations = root.duplicate_attestations ?? []; if (!Array.isArray(rawAttestations) || rawAttestations.length > OPERATOR_IMPORT_MAX_OPS) fail("INVALID_ATTESTATION", "batch.duplicate_attestations", "attestations must be a bounded array"); return { schema: literalAt(root.schema, [OPERATOR_IMPORT_SCHEMA], "batch.schema"), batch_id: textAt(root.batch_id, "batch.batch_id", 128, true), ops: root.ops.map(parseOp), duplicate_attestations: rawAttestations.map(parseAttestation), budget_advance: root.budget_advance === undefined ? undefined : parseBudgetAdvance(root.budget_advance) }; }

function canonicalOp(op: OperatorImportOp): Record<string, unknown> { const base = { kind: op.kind, op_id: op.op_id, record_id: op.record_id, source_locator: op.source_locator, owner: op.owner, source_file: op.source_file, date: op.date }; const optional = (key: string, value: string | undefined) => value === undefined ? {} : { [key]: value }; if (op.kind === "transaction") return { ...base, merchant: op.merchant, amount_cents: op.amount_cents.toString(), transaction_kind: op.transaction_kind, category: op.category, ...optional("card", op.card), ...optional("note", op.note), ...optional("supersedes_record_id", op.supersedes_record_id) }; if (op.kind === "income") return { ...base, amount_cents: op.amount_cents.toString(), source: op.source, ...optional("logged_by", op.logged_by), ...optional("note", op.note), ...optional("archimedes_request_id", op.archimedes_request_id) }; if (op.kind === "btc_buy") return { ...base, source: op.source, sats: op.sats.toString(), price_usd_cents: op.price_usd_cents.toString(), usd_cents: op.usd_cents.toString(), ...optional("note", op.note), ...optional("status", op.status), ...optional("cost_basis_status", op.cost_basis_status), ...optional("logged_by", op.logged_by), ...optional("archimedes_request_id", op.archimedes_request_id) }; return { ...base, merchant: op.merchant, category: op.category, amount_usd_cents: op.amount_usd_cents.toString(), btc_spent_sats: op.btc_spent_sats.toString(), btc_price_cents: op.btc_price_cents.toString(), fee_usd_cents: op.fee_usd_cents.toString(), ...optional("platform", op.platform), ...optional("note", op.note), ...optional("reference", op.reference), budget_effect: op.budget_effect }; }
function canonicalJsonValue(value: unknown): string { if (value === null || typeof value === "string" || typeof value === "boolean") return JSON.stringify(value); if (typeof value === "number") { if (!Number.isSafeInteger(value)) fail("INVALID_CANONICAL_VALUE", "batch", "canonical numbers must be safe integers"); return String(value); } if (Array.isArray(value)) return `[${value.map(canonicalJsonValue).join(",")}]`; const row = objectAt(value, "batch"); return `{${Object.keys(row).sort().map((key) => `${JSON.stringify(key)}:${canonicalJsonValue(row[key])}`).join(",")}}`; }
export function canonicalOperatorImportJson(envelope: OperatorImportEnvelope): string { const budgetAdvance = envelope.budget_advance === undefined ? {} : { budget_advance: { source_file: envelope.budget_advance.source_file, expected_month: envelope.budget_advance.expected_month, target_month: envelope.budget_advance.target_month, expected_updated_at_ms: envelope.budget_advance.expected_updated_at_ms.toString(), history_mode: envelope.budget_advance.history_mode } }; return `${canonicalJsonValue({ schema: envelope.schema, batch_id: envelope.batch_id, ops: envelope.ops.map(canonicalOp), duplicate_attestations: envelope.duplicate_attestations.map((a) => ({ type: a.type, op_ids: [...a.op_ids], semantic_fingerprint: a.semantic_fingerprint, assertion: a.assertion })), ...budgetAdvance })}\n`; }
export async function sha256Hex(value: string): Promise<string> { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join(""); }
export async function digestOperatorImportEnvelope(envelope: OperatorImportEnvelope): Promise<string> { return sha256Hex(canonicalOperatorImportJson(envelope)); }
export function naturalKeyForOperatorImportOp(op: OperatorImportOp): string { return `${op.kind}\u0000${op.source_file}\u0000${op.record_id}`; }
function semanticText(value: string | undefined): string | null { return value === undefined ? null : value.normalize("NFC").toLocaleLowerCase("en-US").replace(/\s+/gu, " ").trim(); }
// A correction's semantic fingerprint is its corrected content only: the
// superseded target is excluded from the production duplicate scan in the
// backend (buildAnalysis), so the guard still binds the corrected row
// against every other live row.
export async function semanticFingerprintForOperatorImportOp(op: OperatorImportOp): Promise<string> { let value: Record<string, unknown>; if (op.kind === "transaction") value = { kind: op.kind, owner: op.owner, date: op.date, amount_cents: op.amount_cents.toString(), merchant: semanticText(op.merchant), category: semanticText(op.category), card: semanticText(op.card) }; else if (op.kind === "income") value = { kind: op.kind, owner: op.owner, date: op.date, amount_cents: op.amount_cents.toString(), source: semanticText(op.source), archimedes_request_id: semanticText(op.archimedes_request_id) }; else if (op.kind === "btc_buy") value = { kind: op.kind, owner: op.owner, date: op.date, sats: op.sats.toString(), price_usd_cents: op.price_usd_cents.toString(), usd_cents: op.usd_cents.toString(), source: semanticText(op.source), archimedes_request_id: semanticText(op.archimedes_request_id) }; else value = op.reference === undefined ? { kind: op.kind, owner: op.owner, date: op.date, merchant: semanticText(op.merchant), amount_usd_cents: op.amount_usd_cents.toString(), btc_spent_sats: op.btc_spent_sats.toString(), btc_price_cents: op.btc_price_cents.toString() } : { kind: op.kind, platform: semanticText(op.platform), reference: semanticText(op.reference) }; return sha256Hex(JSON.stringify(value)); }
function unique(pairs: readonly [string, string][], code: string) { const seen = new Map<string, string>(); for (const [value, opId] of pairs) { const prior = seen.get(value); if (prior !== undefined) throw new OperatorImportValidationError(code, "batch.ops", "batch-internal identity collision", { op_ids: [prior, opId] }); seen.set(value, opId); } }

export async function canonicalizeOperatorImportEnvelope(input: unknown): Promise<CanonicalOperatorImport> {
  const envelope = parseOperatorImportEnvelope(input);
  unique(envelope.ops.map((op) => [op.op_id, op.op_id]), "DUPLICATE_OP_ID"); unique(envelope.ops.map((op) => [op.record_id, op.op_id]), "DUPLICATE_RECORD_ID"); unique(envelope.ops.map((op) => [op.source_locator, op.op_id]), "DUPLICATE_SOURCE_LOCATOR"); unique(envelope.ops.map((op) => [naturalKeyForOperatorImportOp(op), op.op_id]), "DUPLICATE_NATURAL_KEY");
  const ops: CanonicalOperatorImportOp[] = []; for (const op of envelope.ops) ops.push({ ...op, natural_key: naturalKeyForOperatorImportOp(op), semantic_fingerprint: await semanticFingerprintForOperatorImportOp(op) });
  const attestations = new Map(envelope.duplicate_attestations.map((a) => [`${a.op_ids[0]}\u0000${a.op_ids[1]}\u0000${a.semantic_fingerprint}`, a])); const seen = new Map<string, string>();
  for (const op of ops) { const prior = seen.get(op.semantic_fingerprint); if (prior === undefined) { seen.set(op.semantic_fingerprint, op.op_id); continue; } const pair = [prior, op.op_id].sort() as [string, string], key = `${pair[0]}\u0000${pair[1]}\u0000${op.semantic_fingerprint}`; if (!attestations.delete(key)) throw new OperatorImportValidationError("SEMANTIC_DUPLICATE", "batch.ops", "semantic duplicate requires exact fingerprint-bound attestation", { op_ids: pair, semantic_fingerprint: op.semantic_fingerprint }); }
  if (attestations.size !== 0) fail("UNUSED_ATTESTATION", "batch.duplicate_attestations", "attestation does not bind an actual duplicate pair");
  const counts: Record<ImportKind, number> = { transaction: 0, income: 0, btc_buy: 0, btc_bill_pay: 0 }; for (const op of ops) counts[op.kind] += 1; const canonicalJson = canonicalOperatorImportJson(envelope); return { envelope, ops, counts, canonical_json: canonicalJson, manifest_digest: await sha256Hex(canonicalJson) };
}
